exports.error = {
  systemError                         :{ code:40000 , message:'system error'},
  httpMethodIsNotSupportedByThisUrl   :{ code:40001 , message:'http method is not supported by this url'},
  missingParameter                    :{ code:40002 , message:'missing parameter'},
  invalidData                         :{ code:40003 , message:'invalid data'},
  pleaseLoginToTheSystemFirst         :{ code:40004 , message:'please log in to the system first'},
  unauthorized                        :{ code:40005 , message:'unauthorized'},
  accessTokenIsNotCorrect             :{ code:40006 , message:'access token is not correct'},
  passphraseIsNotCorrect              :{ code:40007 , message:'passphrase is not correct'},
  accountHasNotYetBeenVerified        :{ code:41000 , message:'account has not yet been verified'},
  accountIsAlreadyRegistered          :{ code:41001 , message:'account is already registered'},
  accountDoesNotExist                 :{ code:41002 , message:'account does not exist'},
  accountPasswordIsNotCorrect         :{ code:41003 , message:'account password is not correct'},
  accountVerificationCodeIsNotCorrect :{ code:41004 , message:'account verification code is not correct'},
  accountEmailFormatIsNotCorrect      :{ code:41005 , message:'account email format is not correct'},
  accountEmailAlreadyExists           :{ code:41006 , message:'account email already exists'},
  accountYouCantChangeYourLoginEmail  :{ code:41007 , message:'account you cant change your login email'},
  accountPhotoIsNotCorrect            :{ code:41008 , message:'account photo is not correct'},
  accountTheEmailDoesNotExist         :{ code:41009 , message:'account the email does not exist'},
  accountInvitorIsTheSameWithInvitee  :{ code:41010 , message:'account invitor is the same with invite'},
  accountDeserializeUserFailded       :{ code:41011 , message:'account deserialize user failded'},
  accountCreateFaild                  :{ code:41012 , message:'account create faild'},
  accountSignOutFaild                 :{ code:41012 , message:'account signout faild'},
  accountPasswordFormatIsNotCorrect   :{ code:41013 , message:'account password formate is not correct'},
}
exports.succeed = { code:200, message: 'succeed'}
